### ISSUE TITLE
in the mnist.py example, there is utils.print_names_and_shapes() for viewing more than one image's activation

### ISSUE THREAD

**Issue by hamzamk** [philipperemy/keras-activations#10]
hi, is there any workaround utils.print_names_and_shapes ? since utils doesn't have that method

**Comment by philipperemy** [comment]
https://github.com/philipperemy/keras-activations/blob/670b94f4e2710105e015de7e0d16dced41451aeb/examples/utils.py#L1

**Comment by philipperemy** [comment]
Its' there isn't it?
