### ISSUE TITLE
Visualizing activations in RNN while generating network output.

### ISSUE THREAD

**Issue by FilipJanitor** [philipperemy/keras-activations#11]
Hi, I might be missing something but I don`t quite see how I could record activations of layers while simultaneously using my network for predictions. 

What I am trying to do is something like the pictures at the end of this blog [http://karpathy.github.io/2015/05/21/rnn-effectiveness/](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) that are obviously generated using some sort of snapshots of activation.

Basically, when creating the desired sequence I would like to track the activations while feeding the last generated output of the network as next input. However,  the `get_activations` function seems to discard the network output (or at least I don't see where is it explicitly generated).

Is there some way how I could add the network output to the return value? Your tool seems to be pretty straightforward so I am asking instead of trying to hack something from scratch myself :)

Thanks for help!

**Comment by philipperemy** [comment]
@FilipJanitor are you interested in evaluating the network on a sequence step by step?

**Comment by philipperemy** [comment]
Also activations = outputs by the way here.

**Comment by FilipJanitor** [comment]
I know for sure that obtaining the next character of the sequence using the `model.predict(input)` and picking the character using the output probabilities works as expected. I am not sure about the approach you suggested as I don't know how would such iterative feeding affect the internal state of the RNN.  

But what you said about the activations and outputs sounds very promising. Assuming that `predict` returns the outputs of last layer I should be able to reconstruct the output of the last layer from what is returned by  `get_activations` right?  The only thing that is a bit confusing for me is this line: https://github.com/philipperemy/keras-activations/blob/e665695e10bf80d77e0bad21319227fb021007f9/keract/keract.py#L30 what would it get in relation to activations if it was uncommented? 
Thanks!

**Comment by philipperemy** [comment]
This `func` is a Keras function where you define an input tensor and an output tensor. By feeding the input tensor with a numpy matrix, you evaluate the value of the output tensor.

In that case, we list all the layers and we evaluate them one by one. So for your input, you get the output of every layer with this package.

Predict does the same but on the whole model. It will output the outputs of the final layer.

layer_outputs = activations.

Sorry for the confusion ;)

**Comment by philipperemy** [comment]
LSTM has two components when you evaluate a sequence: States and Outputs. We're only talking about outputs here.

**Comment by FilipJanitor** [comment]
Yeah, sorry - I made it more complex than it is. It is all clear now :)
Thanks, for help!

**Comment by philipperemy** [comment]
Ok happy I could help :)
